FROM mysql:8.0

# set the environment variable for MySQL database
# ENV MYSQL_DATABASE=wordpress

# set the default authentication plugin
CMD ["--default-authentication-plugin=mysql_native_password"]


